### ISSUE TITLE
LHCB Docker images and Interface Doc

### ISSUE THREAD

**Issue by emmelmann-fokus** [reTHINK-project/dev-qos-support#14]
- [x] Create docker images for LHCB client and broker for testing
- [x] Document interface to access broker

**Comment by Endebert** [comment]
* [docker images have been created](https://github.com/reTHINK-project/dev-qos-support/tree/master/lhcb/docker)
* docker images are provided by docker hub for the [broker](https://hub.docker.com/r/rethink/lhcb-broker/) and [client ](https://hub.docker.com/r/rethink/lhcb-client/)
* [interface documentation has been added to the readme](https://github.com/reTHINK-project/dev-qos-support/blob/master/lhcb/README.md)

TODOs:
- [ ] document EventSource interface & messages
- [ ] extend WebSocketMessageSchema by Observe & Notify message types

**Comment by emmelmann-fokus** [comment]
Docker images are available on docker hub.

@EwaJan : the images provide a "dummy" client which allows to start integration and interaction with the LHCB.

You may for tests start both on the same machine (assumed to be named myHost.orange.com):
```
docker run -it --net=host --rm rethink/lhcb-broker

docker run -it --rm --net=host rethink/lhcb-client -dummy -name DummyLHCBClient
```

You may have to execute the two commands in two shell windows.

Note that with the commands above, the client assumes the broker to run on localhost; if you want to run the images on different machines, you'll need to pass the IP address of the other in the command line.

Once client and broker run, you may connect to http://myHost.orange.com:8080 (or just http://localhost:8080) to get a test page to access information via the broker.  Select a client (here DummyLHCBClient) and you can on the following page actively pull status information or toggle the buttons to automatically receive status updates.

A detailed description of the interface, i.e. meaning of the retrieved values, as well additional configuration options is available [here](https://github.com/reTHINK-project/dev-qos-support/blob/master/lhcb/README.md).

The overview of the LHCB for reTHINK QoS as provided [here](https://github.com/reTHINK-project/specs/tree/master/qos) shows all interfaces and interactions between components.

Interface *i4* will be the interface between the *brokering* and the LHCB; this is actually what you see graphically when you connect to http://localhost:8080; the actual query will be on http://localhost:8080/.well-known/...... 

As you will need the *LHCB Client ID* to connect, the broker will also need to contact the system of the user via *i2*.  Let's sync on the latter for details.

**Comment by Endebert** [comment]
All done, and docker images are fixed. Closing...
